services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: client
    environment:
      - VITE_GOOGLE_CLIENT_ID=376026541893-13jtelvnv3i8qodlnb7m8olhif8l247a.apps.googleusercontent.com

  express:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: Zafer1998@
      DB_NAME: ecommerce
      REDIS_HOST: redis
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Zafer1998@
      MYSQL_USER: user
      MYSQL_PASSWORD: Zafer1998@
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
